In [14]:
import numpy as np
import util
from NNS import NNS

## 1. Data Loading

In [15]:
retrieval_repository_data = util.load_data('./image_retrieval_repository_data.pkl')

## 2. Data Exploration

In [16]:
print("Image Retrieval Repository Data Shape:", retrieval_repository_data.shape)

Image Retrieval Repository Data Shape: (5000, 257)


## 3. Data Preprocessing 

In [17]:
# remove index column
repository_data_index = retrieval_repository_data[:, 0]
retrieval_repository_data = retrieval_repository_data[:, 1:]

In [18]:
repository_data_index.shape

(5000,)

In [19]:
retrieval_repository_data.shape

(5000, 256)

## 4. Model

In [20]:
nns_model = NNS(k=5)

## 5. Train

In [21]:
nns_model.fit(X_train=retrieval_repository_data)

## 6. Predict

In [22]:
k_nearest = nns_model.predict(retrieval_repository_data[:1000])

100%|██████████| 1000/1000 [00:28<00:00, 34.78it/s]


In [25]:
k_nearest.shape
print(k_nearest)

[[   0  723   32 3892 1431]
 [   1 2854  768 1454  266]
 [   2 2904 3063  311 1216]
 ...
 [ 997 2596 2848 4735 2403]
 [ 998 1805 4474 4183 4974]
 [ 999 1042 2634 3577 1383]]
