## Numpy Practice (0.5 point)

1. Create a 10*10 ndarray object, and the matrix boundary value is 1, and the rest are 0.


In [12]:
#1
import numpy as np

matrix = np.zeros((10, 10), dtype=int)
matrix[0, :] = 1
matrix[-1, :] = 1
matrix[:, 0] = 1
matrix[:, -1] = 1
matrix = matrix.astype(float)
matrix

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

2. Create a 5*5 matrix with each row being 0 to 4

In [11]:
#2
import numpy as np

c = np.array([0, 1, 2, 3, 4])
matrix = np.tile(c, (5, 1))
matrix = matrix.astype(float)
matrix

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

3. Create an 8*8 matrix and fill it with a checkerboard pattern, like [[0,1],[1,0]])

In [10]:
#3
import numpy as np

matrix = np.indices((8, 8)).sum(axis=0) % 2
matrix = matrix.astype(float)
matrix

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

4. output all the odd numbers in the array  
   Example:  
   in:    arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])  
   out:   array([1, 3, 5, 7, 9])  

In [9]:
#4
import numpy as np

array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr = array[array % 2 == 1]
arr

array([1, 3, 5, 7, 9])

5. Normalize a 5x5 random matrix that follows the Gaussian distribution N(4,3).(Z-Score Normalization零均值归一化)

In [15]:
#5
import numpy as np

matrix = np.random.normal(4, 3, (5, 5))
mean = np.mean(matrix)
std = np.std(matrix)
matrix = (matrix - mean) / std
print(matrix)

[[-0.78754133 -0.2281027  -0.13548841  0.96363468 -0.85346228]
 [-0.54664435  1.31031384  2.10410633 -0.01556883 -0.80914382]
 [ 0.48468715  1.20317024  0.71875584  0.62832692  0.68943033]
 [ 0.00753579 -1.04786211 -0.86280122  1.14523471  1.11889639]
 [-0.45112675  0.17756782 -1.67575628 -1.80567708 -1.3324849 ]]


6. Consider a random positive 10x2 matrix representing cartesian coordinates, convert them to polar coordinates.

In [16]:
#6
import numpy as np

x, y = np.random.rand(2, 10)
r = np.sqrt(x ** 2 + y ** 2)
t = np.arctan2(y, x)
print(x, y)
print(r)
print(t)

[0.2677941  0.68035987 0.11461382 0.78614271 0.57300649 0.0957967
 0.1123829  0.54931071 0.10111944 0.10991025] [0.60295194 0.20174336 0.45062758 0.11561895 0.12968819 0.70691883
 0.75899261 0.1174544  0.45641685 0.24041608]
[0.65974595 0.70964071 0.46497478 0.79459934 0.58749933 0.71338015
 0.76726768 0.56172751 0.46748421 0.26434855]
[1.15282759 0.28826521 1.32173465 0.14602437 0.22257937 1.4361038
 1.4237959  0.21064939 1.35276746 1.14199849]


7. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [17]:
#7
import numpy as np

vector = np.array([1, 2, 3, 4, 5])
num_zero = 3
new_len = len(vector) + (len(vector) - 1) * num_zero
new_vector =np.zeros(new_len, dtype=int)
new_vector[::num_zero + 1] = vector
print(new_vector)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


8. What are the result of the following expressions?

0 * np.nan

np.nan == np.nan

np.inf > np.nan

np.nan - np.nan

np.nan in set([np.nan])

0.3 == 3 * 0.1 

(hint1:nan means not a number 

hint2:0.1(10) == 0.0001100110011001100110011001100110011001100110011...(2)

First guess a result, then print the result, and finally find why

In [18]:
#8
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


9. What are the result of the following expressions? (Hint: the type of pn.nan is float)

np.array(0) / np.array(0)

np.array(0) // np.array(0)

np.array([np.nan]).astype(int).astype(float)


First guess a result, then print the result, and finally find why 

In [22]:
#9
import numpy as np

print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan].astype(int).astype(float)))

nan
0


C:\Users\cctt0\AppData\Local\Temp\ipykernel_12148\2552792718.py:4: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\cctt0\AppData\Local\Temp\ipykernel_12148\2552792718.py:5: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


AttributeError: 'list' object has no attribute 'astype'